[workspace.package]
version = "0.1.0"
authors = ["NikVolf"]
edition = "2021"
license = "MIT"
repository = "https://github.com/nikvolf/cargo-gbuild"

[workspace]
resolver = "2"

default-members = ["cli"]

members = [
    "cargo",
    "cli",
]
